version: "3.8"

services:
  node1:
    build: .
    ports:
      - "42069:42069"
    environment:
      SERVER_PORT: 42069
      PEER_ADDRESSES: "node2:42070,node3:42071"

  node2:
    build: .
    ports:
      - "42070:42070"
    environment:
      SERVER_PORT: 42070
      PEER_ADDRESSES: "node3:42071"

  node3:
    build: .
    ports:
      - "42071:42071"
    environment:
      SERVER_PORT: 42071
      PEER_ADDRESSES: "node1:42069"
