version: "3.8"

services:
  node1:
    build: .
    ports:
      - "42069:42069"
    environment:
      SERVER_PORT: 42069
      SERVER_NAME: "node1"
      PEER_ADDRESSES: "node2:42070,node3:42071"

  node2:
    build: .
    ports:
      - "42070:42070"
    environment:
      SERVER_PORT: 42070
      SERVER_NAME: "node2"
      PEER_ADDRESSES: "node4:42072"

  node3:
    build: .
    ports:
      - "42071:42071"
    environment:
      SERVER_PORT: 42071
      SERVER_NAME: "node3"
      PEER_ADDRESSES: "node4:42072"

  node4:
    build: .
    ports:
      - "42072:42072"
    environment:
      SERVER_PORT: 42072
      SERVER_NAME: "node4"
      PEER_ADDRESSES: ""
